### PR TITLE
Json Module

### LINKED ISSUE #2: Json support?
I think JSON encode/decode can be a useful tool.
A similar API and implementation can be used from DOME

https://github.com/domeengine/dome/blob/main/src/modules/json.wren

### PR DESCRIPTION
**Pull request by camilowser**
Closes #2 
Superseeds #4

### CODE REVIEW

**Comment by joshgoebel** [comment]
And it works perfect now. :-)

**Comment by joshgoebel** [comment]
I really wanted some tests and then I saw the great test suite that `wren-json` already had and wondered if we could just borrow that...

```
    ✖ should escape control characters
      Expected "" to equal "\u0001"
```

Would it be hard to make it pass the one failing test from `wren-json`?

**Comment by joshgoebel** [comment]
This is ~ the patch to wren-json I submitted to add this feature over there:

https://github.com/brandly/wren-json/pull/11/files

Dealing with the first < `0x1f` characters is all I need for now.  And would allow me to remove the `wren-json` requirement from `wren-testie` in favor of using built-in JSON support.

I see this:

```
// We have to use C functions for escaping chars
// because a bug in compiler throws error when using \ in strings
// inside Wren files.
```

I'm not sure if this is a problem anymore, so should this just be pulled back inside Wren again now?

**Comment by joshgoebel** [comment]
```
var JSON = Json
var JSONOptions = JsonOptions
var JSONError = JsonError
var JSONEncodable = JsonEncodable
```

I feel like the correct name is JSON so that should be canonical... if someone wants different aliases Wren already provides easy options for that at import time... am I missing something? For any language using CamelCase classes (including Wren) I don't feel like `JsonOptions` is correct.  If one part of the word is an acronym, then it should be all caps in the class-name.  Is there a strong culture in Wren that I'm unaware of to name classes this way? What is the thinking here?

**Comment by joshgoebel** [comment]
I'm quite sold on `parse` for incoming strings (from JS and Ruby to name two), but you're still welcome to talk me out of `stringify` (I added it also because it made the `wren-json` tests pass as-is).  Ruby uses `JSON.generate`, which is nice... `encode` is also nice...  If you're attached to `encode/decode` I'm fine with leaving the pair... but I think we need `parse` as an alias at the least.

**Comment by joshgoebel** [comment]
```
void jsonStreamEscapeChar(WrenVM * vm) {
  ASSERT_SLOT_TYPE(vm, 1, WREN_TYPE_STRING, "value");
  ASSERT_SLOT_TYPE(vm, 2, WREN_TYPE_NUM, "options");
```

Since this is only used internally can these checks be removed - our Wren usage guarantees these checks aren't needed as far as I can see?  And perhaps mark that function private on the Wren side also?

**Comment by clsource** [comment]
> ```
> var JSON = Json
> var JSONOptions = JsonOptions
> var JSONError = JsonError
> var JSONEncodable = JsonEncodable
> ```
> 
> I feel like the correct name is JSON so that should be canonical... if someone wants different aliases Wren already provides easy options for that at import time... am I missing something? For any language using CamelCase classes (including Wren) I don't feel like `JsonOptions` is correct. If one part of the word is an acronym, then it should be all caps in the class-name. Is there a strong culture in Wren that I'm unaware of to name classes this way? What is the thinking here?

you can check here https://github.com/domeengine/dome/pull/83
for the history :)


Basically it was canonical `Json` and as an alias `JSON`. Json was selected as mainly due to the other classes be written as CamelCase

**Comment by joshgoebel** [comment]
Thanks for the history.  Since we're not DOME and don't have though constraints we'll remove this complexity and go with just the uppercase canonicals.

I also don't think `JSON` [or acronyms] are a violation of camel-case either. :-)  But DOME can be DOME, or Dome, lol. 💯

**Comment by joshgoebel** [comment]
@clsource @camilowser Thanks for all the hard work and effort on this!

**Pull request merged**
