### PR TITLE
[WIP] Json

### PR DESCRIPTION
**Pull request by camilowser**
This should work instead of #3

### CODE REVIEW

**Comment by clsource** [comment]
closes #2

**Comment by joshgoebel** [comment]
Do you see the checkbox now?  I still evidently can't push.

**Comment by camilowser** [comment]
image

**Comment by clsource** [comment]
Clearly this is super odd. GH bug? probably

**Comment by joshgoebel** [comment]
OK, well you have the checkbox now.... so now perhaps it's just a bug in `gh` (the GitHub cli)... let me try to push to the branch manually.

**Comment by clsource** [comment]
I sent a bug report to GH

**Comment by joshgoebel** [comment]
I wonder if now the problem is it's a fork of a fork... I'm not sure GH respects the relationships if they go that deep.  It might be expected the fork to be of the main repo here.  Not a fork of your own `clsource` fork.

```
% git push clsource json
ERROR: Permission to camilowser/wren-essentials.git denied to joshgoebel.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by joshgoebel** [comment]
I'm starting to wonder if it's because `NinjasCL-labs` is an organization and you aren't just using your personal GitHub to fork? (why #3 failed) 

Can you make a simple fork of the main repo to `clsource` and then a PR from `clsource` (this or just something stupid) and see if that fixes it [ie, I'll try it again]?

**Comment by clsource** [comment]
sure lets see what can be done

**Pull request closed without merging**
