### PR TITLE
[feat] Added utf8 upcase and downcase

### LINKED ISSUE #11: Strings: UTF-8 compatible `toLower`, `toUpper`, `downcase`, `upcase`
Ref: https://github.com/sheredom/utf8.h

Lets add:

- [ ] `toLower`
- [ ] `toUpper`
- [ ] `downcase(_)` - now UTF-8 compatible
- [ ] `upcase(_)` - now UTF-8 compatible
- [ ] `capitalize` - I assume we'd bump this to (to build on the new utf8 stuff)
- [ ] `titlecase` - I assume we'd bump this to (to build on the new utf8 stuff)

Is there any reason to keep the existing upcase/downcase around as pure ASCII versions?

### PR DESCRIPTION
**Pull request by clsource**
closes #11

### CODE REVIEW

**Comment by joshgoebel** [comment]
Please rebase onto main so that this PR/diff only includes your changes and not all the other recent work.  If all the build stuff really needed bumped can you please do it in a separate commit so it's not mixed with the actual changes that need review.

I'm quickly losing patience with the build scripts being checked into git - even though there are good reasons. :) But I dunno what to do...

**Comment by clsource** [comment]
Maybe a github action can be done to update the build scripts on merging into main
so they will always have the latest version with the included libs.

As I see the build scripts they lacked the json module.

**Comment by joshgoebel** [comment]
> Maybe a github action can be done to update the build scripts on merging into main
so they will always have the latest version with the included libs.

Not opposed to that if it worked reliably. :-)  I think the problem is I only update the Mac scripts that I need for building... and there is no "release" process yet to make sure they all get bumped.

I can update main and you can rebase or you could just split the PR into two commits - the actual changes + the build stuff in a  separate commit.

**Comment by clsource** [comment]
I will use 2 prs

**Pull request closed without merging**
